/*
 * Java domain class for entity "EserviceBuildingDetails" 
 * Created on 2022-11-18 ( Date ISO 2022-11-18 - Time 11:38:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-18 ( 11:38:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import jakarta.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.BuildingRiskDetails;
import com.maan.eway.bean.BuildingRiskDetailsId;
import com.maan.eway.bean.EserviceBuildingDetails;
/**
 * <h2>EserviceBuildingDetailsRepository</h2>
 *
 * createdAt : 2022-11-18 - Time 11:38:42
 * <p>
 * Description: "EserviceBuildingDetails" Repository
 */
 
 
 
public interface BuildingRiskDetailsRepository  extends JpaRepository<BuildingRiskDetails,BuildingRiskDetailsId > , JpaSpecificationExecutor<BuildingRiskDetails> {

	List<BuildingRiskDetails> findByQuoteNo(String quoteNo);

	Long countByQuoteNo(String quoteNo);

	@Transactional
	void deleteByQuoteNo(String quoteNo);

	List<BuildingRiskDetails> findByQuoteNoOrderByRiskIdAsc(String quoteNo);

	BuildingRiskDetails findByQuoteNoAndSectionIdAndStatusNot(String quoteNo, String sectionId, String string);
	
	BuildingRiskDetails findByRequestReferenceNoAndSectionIdAndStatusNot(String reqno, String sectionId, String string);



}
