/*
 * Java domain class for entity "DocumentMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import jakarta.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.CoverDocumentMaster;
import com.maan.eway.bean.CoverDocumentMasterId;
import com.maan.eway.bean.DocumentTransactionDetails;
import com.maan.eway.bean.DocumentTransactionDetailsId;

 
public interface DocumentTransactionDetailsRepository  extends JpaRepository<DocumentTransactionDetails,DocumentTransactionDetailsId > , JpaSpecificationExecutor<DocumentTransactionDetails> {

	List<DocumentTransactionDetails> findByQuoteNo(String quoteNo);

	@Transactional
	void deleteByQuoteNoAndUniqueIdAndId(String quoteNo, Integer valueOf, String id);

	DocumentTransactionDetails findByQuoteNoAndUniqueIdAndId(String quoteNo, Integer valueOf, String id);

	Long countByQuoteNo(String quoteNo);


	List<DocumentTransactionDetails> findByQuoteNoAndSectionIdAndRiskId(String quoteNo, Integer valueOf,
			Integer integer);

	List<DocumentTransactionDetails> findByQuoteNoAndSectionIdAndProductIdAndCompanyId(String quoteNo, Integer valueOf,
			Integer productId, String companyId);

	List<DocumentTransactionDetails> findByQuoteNoAndProductIdAndCompanyId(String quoteNo, Integer valueOf,
			String insuranceId);

	List<DocumentTransactionDetails> findByQuoteNoAndSectionId(String quoteNo, Integer valueOf);

	Long countByQuoteNoAndLocationIdNotIn(String quoteNo, List<Integer> locIds);

	@Transactional
	void deleteByQuoteNoAndLocationIdNotIn(String quoteNo, List<Integer> locIds);

	Long countByQuoteNoAndLocationIdAndSectionIdAndIdTypeAndIdNotIn(String quoteNo, Integer valueOf,Integer valueOf2, String string,
			List<String> nationalityIds);

	void deleteByQuoteNoAndLocationIdAndSectionIdAndIdTypeAndIdNotIn(String quoteNo, Integer valueOf,Integer valueOf2, String string,
			 List<String> nationalityIds);

	Long countByRequestReferenceNoAndLocationIdNotIn(String requestno, List<Integer> locIds);

	void deleteByRequestReferenceNoAndLocationIdNotIn(String requestno, List<Integer> locIds);

	

}
