/*
 * Java domain class for entity "DocumentMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.CoverDocumentMaster;
import com.maan.eway.bean.CoverDocumentMasterId;
import com.maan.eway.bean.DocumentUniqueDetails;
import com.maan.eway.bean.DocumentUniqueDetailsId;

 
public interface DocumentUniqueDetailsRepository  extends JpaRepository<DocumentUniqueDetails,DocumentUniqueDetailsId > , JpaSpecificationExecutor<DocumentUniqueDetails> {

	List<DocumentUniqueDetails> findByUniqueIdIn(List<Integer> uniqueIds);

	DocumentUniqueDetails findByUniqueId(Integer valueOf);

	List<DocumentUniqueDetails> findByIdTypeAndIdInOrderByEntryDateDesc(String idType, List<String> ids);

}
