/*
 * Java domain class for entity "EndtTypeMaster" 
 * Created on 2023-03-01 ( Date ISO 2023-03-01 - Time 11:29:43 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-03-01 ( 11:29:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EndtTypeMaster;
import com.maan.eway.bean.EndtTypeMasterId;
/**
 * <h2>EndtTypeMasterRepository</h2>
 *
 * createdAt : 2023-03-01 - Time 11:29:43
 * <p>
 * Description: "EndtTypeMaster" Repository
 */
 
 
 
public interface EndtTypeMasterRepository  extends JpaRepository<EndtTypeMaster,EndtTypeMasterId > , JpaSpecificationExecutor<EndtTypeMaster> {
	/*
	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatus(String companyId, Integer productId, String status);
	
	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusOrderByPriorityAsc(String companyId, Integer productId, String status);

	EndtTypeMaster findByCompanyIdAndProductIdAndStatusAndEndtTypeId(String companyId, Integer productId,
			String string, Integer parseInt);
	*/

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusAndEffectiveDateStartLessThanEqualAndEffectiveDateEndGreaterThanEqual(String companyId, Integer productId, String status, Date date, Date date2);

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusAndEffectiveDateStartLessThanEqualAndEffectiveDateEndGreaterThanEqualOrderByPriorityAsc(
			String companyId, Integer productId, String status, Date date, Date date2);

	EndtTypeMaster findByCompanyIdAndProductIdAndStatusAndEndtTypeIdAndEffectiveDateStartLessThanEqualAndEffectiveDateEndGreaterThanEqual(
			String companyId, Integer productId, String status,Integer endttypeid, Date date, Date date2);

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusAndEffectiveDateStartLessThanEqualAndEffectiveDateEndGreaterThanEqualAndEndtTypeIdOrderByPriorityAsc(
			String companyId, Integer valueOf, String string, Date date, Date date2, Integer valueOf2);

	List<EndtTypeMaster> findByEndtTypeCategoryIdAndEndtTypeIdAndCompanyIdAndProductIdOrderByAmendIdDesc(
			Integer integer, Integer valueOf, String companyId, Integer integer2);

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusAndEffectiveDateStartLessThanEqualAndEffectiveDateEndGreaterThanEqualAndEndtTypeIdOrderByAmendIdDesc(
			String companyId, Integer productId, String string, Date effectiveDate, Date effectiveDate2,
			Integer endtType);

	EndtTypeMaster findByCompanyIdAndProductIdAndStatusAndEndtTypeId(String companyId, Integer productId, String string,
			Integer endtTypeId);

	/*List<EndtTypeMaster> findByCompanyIdAndProductIdAndStatusAndEndtTypeId(String companyId, Integer productId,
			String string, Integer endtType);
*/
	

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndEndtTypeId(String companyId, Integer productId,
			Integer endtType);

	List<EndtTypeMaster> findByCompanyIdAndProductIdAndEndtTypeIdAndStatusOrderByAmendIdDesc(String companyId,Integer productId, Integer endtType, String status);


}
