/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import jakarta.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EserviceBuildingDetails;
import com.maan.eway.bean.EserviceBuildingDetailsId;
import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.EserviceMotorDetailsId;

 
 
public interface EServiceBuildingDetailsRepository  extends JpaRepository<EserviceBuildingDetails,EserviceBuildingDetailsId > , JpaSpecificationExecutor<EserviceBuildingDetails> {

//	EserviceBuildingDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer valueOf);

	List<EserviceBuildingDetails> findByRequestReferenceNoOrderByRiskIdAsc(String requestReferenceNo);

//	EserviceBuildingDetails findByQuoteNo(String quoteNo);

//	EserviceBuildingDetails findByRequestReferenceNoAndRiskId(String requestReferenceNo, String riskId);

	List<EserviceBuildingDetails> findByRequestReferenceNo(String requestReferenceNo);

	List<EserviceBuildingDetails> findByEndtPrevPolicyNo(String endtPrevPolicyNo);

	Long countByRequestReferenceNo(String requestReferenceNo);

	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndSectionId(String requestReferenceNo, Integer locId,
			String string);

	@Transactional
	void deleteByRequestReferenceNoAndRiskIdAndSectionIdNotIn(String requestReferenceNo, Integer riskId,
			List<String> optedSections);

	EserviceBuildingDetails findByQuoteNoAndSectionId(String quoteNo, String sectionId);
	

	List<EserviceBuildingDetails> findByRequestReferenceNoAndStatusNotIn(String requestReferenceNo,
			List<String> statusesNot);

	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionId(String requestReferenceNo, String string);

	EserviceBuildingDetails findByRequestReferenceNoAndSectionIdAndStatus(String requestReferenceNo, String string,
			String string2);


	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionIdAndRiskIdNotIn(String requestReferenceNo,
			String string, List<Integer> riskIds);

	List<EserviceBuildingDetails> findByRequestReferenceNoAndSectionIdAndRiskId(String requestReferenceNo,
			String string, Integer i);
	
	List<EserviceBuildingDetails> findByRequestReferenceNoAndProductId(String requestReferenceNo,
			 String pid);


	List<EserviceBuildingDetails> findAllByRequestReferenceNoAndSectionId(String requestReferenceNo, String sectionId);
	

	EserviceBuildingDetails findByRiskIdAndRequestReferenceNoAndSectionId(Integer riskid,String requestReferenceNo, String string);

	List<EserviceBuildingDetails> findByRequestReferenceNoAndRiskId(String requestReferenceNo, Integer valueOf);

	EserviceBuildingDetails findByRequestReferenceNoAndRiskIdAndSectionIdAndLocationId(String requestReferenceNo, Integer valueOf,String sectionid,Integer locationid);

	List<EserviceBuildingDetails> findByRequestReferenceNoAndLocationId(String requestReferenceNo, Integer valueOf);

}
