/*
 * Java domain class for entity "PolicyHolderInfo" 
 * Created on 2023-10-12 ( Date ISO 2023-10-12 - Time 18:15:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-10-12 ( 18:15:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.eway.bean.PolicyHolderInfo;
import com.maan.eway.bean.PolicyHolderInfoId;
/**
 * <h2>PolicyHolderInfoRepository</h2>
 *
 * createdAt : 2023-10-12 - Time 18:15:33
 * <p>
 * Description: "PolicyHolderInfo" Repository
 */
 
 
 
public interface PolicyHolderInfoRepository  extends JpaRepository<PolicyHolderInfo,PolicyHolderInfoId > , JpaSpecificationExecutor<PolicyHolderInfo> {

	@Query(nativeQuery = true, value = "SELECT FN_GET_CODE(:type,:text,:company,:country,:product,:section)  FROM DUAL")
	String fuGetCode(@Param("type") String type,@Param("text") String text,@Param("company") String company,@Param("country") String country,@Param("product") String product,@Param("section") String section);

	PolicyHolderInfo findByReqRegNumber(String reqRegNumber);
	 


}
