/*
 * Java domain class for entity "TiraTrackingDetails" 
 * Created on 2023-06-09 ( Date ISO 2023-06-09 - Time 15:34:13 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-06-09 ( 15:34:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.web.PageableDefault;

import com.maan.eway.bean.TiraTrackingDetails;
import com.maan.eway.bean.TiraTrackingDetailsId;
/**
 * <h2>TiraTrackingDetailsRepository</h2>
 *
 * createdAt : 2023-06-09 - Time 15:34:13
 * <p>
 * Description: "TiraTrackingDetails" Repository
 */
 
 
 
public interface TiraTrackingDetailsRepository  extends JpaRepository<TiraTrackingDetails,TiraTrackingDetailsId > , JpaSpecificationExecutor<TiraTrackingDetails> {

	List<TiraTrackingDetails> findByRequestIdAndStatusAndMethodNameOrderByEntryDateDesc(String requestId,String status,String methodName);

	List<TiraTrackingDetails> findByPolicyNoOrderByEntryDateDesc(String quoteNo,@PageableDefault(size = 10, direction = Sort.Direction.DESC, sort = "entryDate") Pageable page); 

}
