/*
 * Java domain class for entity "PolicyHolderInfo" 
 * Created on 2023-10-12 ( Date ISO 2023-10-12 - Time 18:15:33 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Domain class for entity "PolicyHolderInfo"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class PolicyHolderInfoDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Policyholdertype")
    private String     policyHolderType ;
	@JsonProperty("Policyholderidtype")
    private String     policyHolderIdType ;
	@JsonProperty("Policyholderidnumber")
    private String     policyHolderIdNumber ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Policyholdername")
    private String     policyHolderName ;
	@JsonProperty("Dob")
    private Date       dob          ;
	@JsonProperty("Gender")
    private String     gender       ;
	@JsonProperty("Genderdesc")
    private String     genderDesc   ;
	@JsonProperty("Policyholdertypedesc")
    private String     policyHolderTypeDesc ;
	@JsonProperty("Policyholderiddesc")
    private String     policyHolderIdDesc ;
	@JsonProperty("Countrycode")
    private String     countryCode  ;
	@JsonProperty("Countryname")
    private String     countryName  ;
	@JsonProperty("Regioncode")
    private String     regionCode   ;
	@JsonProperty("Regionname")
    private String     regionName   ;
	@JsonProperty("Districtcode")
    private String     districtCode ;
	@JsonProperty("Districtname")
    private String     districtName ;
	@JsonProperty("Street")
    private String     street       ;
	@JsonProperty("Pincode")
    private String     pinCode      ;
	@JsonProperty("Mobileno")
    private String     mobileNo     ;
	@JsonProperty("Fax")
    private String     fax          ;
	@JsonProperty("Email")
    private String     email        ;
	@JsonProperty("Coreappcode")
    private String     coreAppCode  ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Effectivedatestart")
    private Date       effectiveDateStart ;
	@JsonProperty("Effectivedateend")
    private Date       effectiveDateEnd ;
	@JsonProperty("Amendid")
    private Integer    amendId      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("MobileCode")
    private String     mobileCode;
    
	@JsonProperty("REQ_REG_NUMBER")
    private String     reqRegNumber;
    //--- ENTITY LINKS ( RELATIONSHIP )
	@JsonProperty("CustomerReferenceNo")
    private String     customerId;
    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
