/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:50:42 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:50:42 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "AcExecutiveProductMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(AcExecutiveProductMasterId.class)
@Table(name="ac_executive_product_master")


public class AcExecutiveProductMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AC_EXECUTIVE_ID", nullable=false, length=20)
    private String     acExecutiveId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START", nullable=false)
    private Date       effectiveDateStart ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END", nullable=false)
    private Date       effectiveDateEnd ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="AC_EXECUTIVE_NAME", length=100)
    private String     acExecutiveName ;

    @Column(name="PRODUCT_NAME", length=100)
    private String     productName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="SUM_INSURED_START")
    private Double     sumInsuredStart ;

    @Column(name="SUM_INSURED_END")
    private Double     sumInsuredEnd ;

    @Column(name="EXIST_CUST_COMM_PERCENT")
    private Double     existCustCommPercent ;

    @Column(name="NEW_CUST_COMM_PERCENT")
    private Double     newCustCommPercent ;

    @Column(name="RENEWAL_CUST_COMM_PERCENT")
    private Double     renewalCustCommPercent ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="CORE_APP_CODE", length=20)
    private String     coreAppCode ;

    @Column(name="REGULATORY_CODE", length=20)
    private String     regulatoryCode ;

    @Column(name="BANK_NAME", length=100)
    private String     bankName ;

    @Column(name="BANK_CODE", length=20)
    private String     bankCode ;

    @Column(name="OA_CODE", length=20)
    private String     oaCode ;

    @Column(name="AGENCY_CODE", length=20)
    private String     agencyCode ;

    @Column(name="USER_TYPE", length=20)
    private String     userType ;

    @Column(name="SUB_USER_TYPE", length=20)
    private String     subUserType ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



