/*
 * Created on 2024-06-19 ( 16:50:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "BrokerCommissionDetails" ( stored in table "broker_commission_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class BrokerCommissionDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    id ;
    
    private String     agencyCode ;
    
    private String     oaCode ;
    
    private String     loginId ;
    
    private String     companyId ;
    
    private String     productId ;
    
    private String     policyType ;
    
    private Integer    amendId ;
    
     
}
