/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:50:59 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:50:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "CommonDataDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CommonDataDetailsId.class)
@Table(name="common_data_details")


public class CommonDataDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;
    
    @Id
    @Column(name="LOCATION_ID", nullable=false)
    private Integer    locationId ;

    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    @Id
    @Column(name="SECTION_ID", nullable=false, length=20)
    private String     sectionId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="LOCATION_NAME", length=20)
    private String     locationName ;
    
    @Column(name="PRODUCT_ID", length=20)
    private String     productId ;

    @Column(name="PRODUCT_DESC", length=100)
    private String     productDesc ;

    @Column(name="OCCUPATION_DESC", length=100)
    private String     occupationDesc ;

    @Column(name="OCCUPATION_TYPE", length=100)
    private String     occupationType ;

    @Column(name="SECTION_DESC", length=100)
    private String     sectionDesc ;

    @Column(name="COMPANY_ID", length=20)
    private String     companyId ;

    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="BRANCH_NAME", length=100)
    private String     branchName ;

    @Column(name="CATEGORY_ID", length=20)
    private String     categoryId ;

    @Column(name="SUM_INSURED")
    private BigDecimal       sumInsured ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="COUNT")
    private Integer    count ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="ADMIN_LOGIN_ID", length=100)
    private String     adminLoginId ;

    @Column(name="ADMIN_REMARKS", length=100)
    private String     adminRemarks ;

    @Column(name="REFERAL_REMARKS", length=1000)
    private String     referalRemarks ;

    @Column(name="REJECT_REASON", length=100)
    private String     rejectReason ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="BROKER_CODE", length=100)
    private String     brokerCode ;

    @Column(name="AC_EXECUTIVE_ID", length=100)
    private String     acExecutiveId ;

    @Column(name="APPLICATION_ID", length=100)
    private String     applicationId ;

    @Column(name="BROKER_BRANCH_CODE", length=100)
    private String     brokerBranchCode ;

    @Column(name="BROKER_BRANCH_NAME", length=100)
    private String     brokerBranchName ;

    @Column(name="BDM_CODE", length=100)
    private String     bdmCode ;

    @Column(name="QUOTE_NO", length=100)
    private String     quoteNo ;

    @Column(name="CUSTOMER_ID", length=100)
    private String     customerId ;

    @Column(name="OLD_REQ_REF_NO", length=100)
    private String     oldReqRefNo ;

    @Column(name="BENEFIT_COVER_MONTH")
    private Integer    benefitCoverMonth ;

    @Column(name="SALARY_PER_ANNUM")
    private Double     salaryPerAnnum ;

    @Column(name="POLICY_PERIOD", length=100)
    private String     policyPeriod ;

    @Column(name="EXCHANGE_RATE")
    private Double     exchangeRate ;

    @Column(name="CURRENCY", length=20)
    private String     currency ;

    @Column(name="AGENCY_CODE", length=100)
    private String     agencyCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICY_START_DATE")
    private Date       policyStartDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICY_END_DATE")
    private Date       policyEndDate ;

    @Column(name="ACTUAL_PREMIUM_FC")
    private Double     actualPremiumFc ;

    @Column(name="ACTUAL_PREMIUM_LC")
    private Double     actualPremiumLc ;

    @Column(name="OVERALL_PREMIUM_LC")
    private Double     overallPremiumLc ;

    @Column(name="OVERALL_PREMIUM_FC")
    private Double     overallPremiumFc ;

    @Column(name="HAVEPROMOCODE", length=100)
    private String     havepromocode ;

    @Column(name="PROMOCODE", length=100)
    private String     promocode ;

    @Column(name="CUSTOMER_NAME", length=100)
    private String     customerName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DOB")
    private Date       dob ;

    @Column(name="JOB_JOINING_MONTH", length=100)
    private String     jobJoiningMonth ;

    @Column(name="BETWEEN_DISCONTINUED", length=10)
    private String     betweenDiscontinued ;

    @Column(name="ETHICAL_WORK_INVOLVED", length=10)
    private String     ethicalWorkInvolved ;

    @Column(name="BANK_CODE", length=100)
    private String     bankCode ;

    @Column(name="ENDT_PREMIUM")
    private Double     endtPremium ;

    @Column(name="NATURE_OF_BUSINESS_ID")
    private Long       natureOfBusinessId ;

    @Column(name="NATURE_OF_BUSINESS_DESC", length=100)
    private String     natureOfBusinessDesc ;

    @Column(name="TOTAL_NO_OF_EMPLOYEES")
    private Long       totalNoOfEmployees ;

    @Column(name="TOTAL_EXCLUDED_EMPLOYEES")
    private Long       totalExcludedEmployees ;

    @Column(name="TOTAL_REJOINED_EMPLOYEES")
    private Long       totalRejoinedEmployees ;

    @Column(name="ACCOUNT_OUTSTANDING_EMPLOYEES")
    private Long       accountOutstandingEmployees ;

    @Column(name="TOTAL_OUTSTANDING_AMOUNT")
    private Double     totalOutstandingAmount ;

    @Column(name="ACCOUNT_AUDITENT_TYPE")
    private Integer    accountAuditentType ;

    @Column(name="AUDITENT_TYPE_DESC", length=100)
    private String     auditentTypeDesc ;

    @Column(name="INDUSTRY_ID", length=100)
    private String     industryId ;

    @Column(name="INDUSTRY_NAME", length=100)
    private String     industryName ;

    @Column(name="LIABILITY_SI")
    private Double     liabilitySi ;

    @Column(name="FID_EMP_COUNT")
    private Long       fidEmpCount ;

    @Column(name="FID_EMP_SI")
    private Double     fidEmpSi ;

    @Column(name="EMP_LIABILITY_SI")
    private Double     empLiabilitySi ;

    @Column(name="PERSONAL_LIABILITY_SI")
    private Double     personalLiabilitySi ;

    @Column(name="PERSONAL_LIABILITY_OCCUPATION", length=100)
    private String     personalLiabilityOccupation ;

    @Column(name="PERSONAL_LIABILITY_CATEGORY")
    private Double     personalLiabilityCategory ;

    @Column(name="TIRA_COVER_NOTE_NO", length=100)
    private String     tiraCoverNoteNo ;

    @Column(name="ENDORSEMENT_TYPE")
    private Integer    endorsementType ;

    @Column(name="ENDORSEMENT_TYPE_DESC", length=100)
    private String     endorsementTypeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="ENDORSEMENT_REMARKS", length=100)
    private String     endorsementRemarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_EFFDATE")
    private Date       endorsementEffdate ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="ENDT_PREV_POLICY_NO", length=100)
    private String     endtPrevPolicyNo ;

    @Column(name="ENDT_PREV_QUOTE_NO", length=100)
    private String     endtPrevQuoteNo ;

    @Column(name="ENDT_COUNT")
    private Double     endtCount ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Column(name="IS_FINYN", length=10)
    private String     isFinyn ;

    @Column(name="ENDT_CATEG_DESC", length=100)
    private String     endtCategDesc ;

    @Column(name="COMMISSION_PERCENTAGE")
    private Double     commissionPercentage ;

    @Column(name="VAT_COMMISSION")
    private Double     vatCommission ;

    @Column(name="LIABILITY_SI_LC")
    private Double     liabilitySiLc ;

    @Column(name="FID_EMP_SI_LC")
    private Double     fidEmpSiLc ;

    @Column(name="EMP_LIABILITY_SI_LC")
    private Double     empLiabilitySiLc ;

    @Column(name="PERSONAL_LIABILITY_SI_LC")
    private Double     personalLiabilitySiLc ;

    @Column(name="SUM_INSURED_LC")
    private Double     sumInsuredLc ;

    @Column(name="AOO_SUMINSURED_LC")
    private Double     aooSuminsuredLc ;

    @Column(name="AGG_SUMINSURED_LC")
    private Double     aggSuminsuredLc ;

    @Column(name="SUB_USER_TYPE", length=20)
    private String     subUserType ;

    @Column(name="AOO_SUMINSURED")
    private Double     aooSuminsured ;

    @Column(name="AGG_SUMINSURED")
    private Double     aggSuminsured ;

    @Column(name="CD_REFNO")
    private Double     cdRefno ;

    @Column(name="MS_REFNO")
    private Double     msRefno ;

    @Column(name="VD_REFNO")
    private Double     vdRefno ;

    @Column(name="SOURCE_TYPE", length=100)
    private String     sourceType ;

    @Column(name="CUSTOMER_CODE", length=100)
    private String     customerCode ;

    @Column(name="SALE_POINT_CODE", length=200)
    private String     salePointCode ;

    @Column(name="FINALIZE_YN", length=2)
    private String     finalizeYn ;

    @Column(name="PRODUCT_TURNOVER_SI")
    private Double     productTurnoverSi ;

    @Column(name="PRODUCT_TURNOVER_SI_LC")
    private Double     productTurnoverSiLc ;

    @Column(name="ANY_ACCIDENT_SI")
    private Double     anyAccidentSi ;

    @Column(name="ANY_ACCIDENT_SI_LC")
    private Double     anyAccidentSiLc ;

    @Column(name="INSURANCE_PERIOD_SI")
    private Double     insurancePeriodSi ;

    @Column(name="INSURANCE_PERIOD_SI_LC")
    private Double     insurancePeriodSiLc ;

    @Column(name="BROKER_TIRA_CODE", length=100)
    private String     brokerTiraCode ;

    @Column(name="SOURCE_TYPE_ID", length=20)
    private String     sourceTypeId ;

    @Column(name="VAT_PREMIUM")
    private Double     vatPremium ;

    @Column(name="ENDT_VAT_PREMIUM")
    private Double     endtVatPremium ;

    @Column(name="OTHER_OCCUPATION", length=200)
    private String     otherOccupation ;

    @Column(name="RELATION_TYPE", length=100)
    private String     relationType ;

    @Column(name="RELATION_TYPE_DESC", length=100)
    private String     relationTypeDesc ;

    @Column(name="NICK_NAME", length=200)
    private String     nickName ;

    @Column(name="AGE")
    private Integer    age ;

    @Column(name="TTD_SUM_INSURED")
    private Integer    ttdSumInsured ;

    @Column(name="ME_SUM_INSURED")
    private Integer    meSumInsured ;

    @Column(name="FE_SUM_INSURED")
    private Integer    feSumInsured ;

    @Column(name="TTD_SUM_INSURED_LC")
    private Integer    ttdSumInsuredLc ;

    @Column(name="ME_SUM_INSURED_LC")
    private Integer    meSumInsuredLc ;

    @Column(name="FE_SUM_INSURED_LC")
    private Integer    feSumInsuredLc ;

    @Column(name="PTD_SUM_INSURED")
    private Integer    ptdSumInsured ;

    @Column(name="PTD_SUM_INSURED_LC")
    private Integer    ptdSumInsuredLc ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



