/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-05-15 ( Date ISO 2024-05-15 - Time 16:21:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-05-15 ( 16:21:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "ContentAndRisk"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ContentAndRiskId.class)
@Table(name="content_and_risk")


public class ContentAndRisk implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 

    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    @Id
    @Column(name="SECTION_ID", nullable=false, length=20)
    private String     sectionId ;

    @Id
    @Column(name="ITEM_ID", nullable=false)
    private Integer    itemId ;

    
    @Id
    @Column(name="SERIAL_NO_DESC", nullable=false, length=500)
    private String     serialNoDesc ;
    
	@Id	
	@Column(name = "LOCATION_ID", nullable = false)
	private Integer locationId;
//	
//	@Column(name = "SNO")
//	private Long sno;


    //--- ENTITY DATA FIELDS 
	@Column(name="QUOTE_NO",length=20)
    private String     quoteNo ;

    @Column(name="SECTION_DESC", length=100)
    private String     sectionDesc ;

    @Column(name="ITEM_DESC", nullable=false, length=100)
    private String     itemDesc ;

    @Column(name="ITEM_VALUE")
    private BigDecimal       itemValue ;

    @Column(name="SUM_INSURED")
    private BigDecimal       sumInsured ;

    @Column(name="SERIAL_NO")
    private String       serialNo ;

    @Column(name="MAKE_AND_MODEL", length=100)
    private String     makeAndModel ;

    @Column(name="TYPE", length=20)
    private String     type ;

    @Column(name="TYPE_DESC", length=100)
    private String     typeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="PURCHASE_YEAR", length=10)
    private String     purchaseYear ;

    @Column(name="PURCHASE_MONTH", length=10)
    private String     purchaseMonth ;

    @Column(name="ENDORSEMENT_TYPE")
    private Integer    endorsementType ;

    @Column(name="ENDORSEMENT_TYPE_DESC", length=100)
    private String     endorsementTypeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="ENDORSEMENT_REMARKS", length=100)
    private String     endorsementRemarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_EFFDATE")
    private Date       endorsementEffdate ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="ENDT_PREV_POLICY_NO", length=100)
    private String     endtPrevPolicyNo ;

    @Column(name="ENDT_PREV_QUOTE_NO", length=100)
    private String     endtPrevQuoteNo ;

    @Column(name="ENDT_COUNT")
    private Double     endtCount ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Column(name="IS_FINYN", length=10)
    private String     isFinyn ;

    @Column(name="ENDT_CATEG_DESC", length=100)
    private String     endtCategDesc ;

    @Column(name="CONTENT_RISK_DESC", length=500)
    private String     contentRiskDesc ;

    @Column(name="LOCATION_NAME", length=100)
    private String     locationName ;

    @Column(name="NAME", length=100)
    private String     name ;

    @Column(name="BRAND", length=100)
    private String     brand ;

    @Column(name="SUM_INSURED_LC")
    private BigDecimal     sumInsuredLc ;

    @Column(name="MANUFACTURE_YEAR", length=20)
    private String     manufactureYear ;
    @Column(name = "COMPANY_ID", length = 20)
    private String companyId;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



