/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "CoverMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CoverMasterId.class)
@Table(name="cover_master")


public class CoverMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;

    @Id
    @Column(name="SUB_COVER_ID", nullable=false)
    private Integer    subCoverId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COVER_NAME", length=100)
    private String     coverName ;

    @Column(name="COVER_DESC", length=300)
    private String     coverDesc ;

    @Column(name="SUB_COVER_YN", length=1)
    private String     subCoverYn ;

    @Column(name="SUB_COVER_NAME", length=300)
    private String     subCoverName ;

    @Column(name="SUB_COVER_DESC", length=300)
    private String     subCoverDesc ;

    @Column(name="RATING_ID")
    private Integer    ratingId ;

    @Column(name="COVERAGE_TYPE", length=10)
    private String     coverageType ;

    @Column(name="COVERAGE_TYPE_DESC", length=100)
    private String     coverageTypeDesc ;

    @Column(name="COVERAGE_LIMIT")
    private Double     coverageLimit ;

    @Column(name="CALC_TYPE", length=2)
    private String     calcType ;

    @Column(name="CALC_TYPE_DESC", length=100)
    private String     calcTypeDesc ;

    @Column(name="BASE_RATE")
    private Double     baseRate ;

    @Column(name="MIN_PREMIUM")
    private Double     minPremium ;

    @Column(name="MIN_SUMINSURED")
    private Double     minSuminsured ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    @Column(name="TOOL_TIP", length=100)
    private String     toolTip ;

    @Column(name="REGULATORY_CODE", length=20)
    private String     regulatoryCode ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="MAX_SUMINSURED")
    private Double     maxSuminsured ;

    @Column(name="FACTOR_TYPE_ID")
    private Integer    factorTypeId ;

    @Column(name="CORE_APP_CODE", length=20)
    private String     coreAppCode ;

    @Column(name="IS_TAX_EXCEMPTED", length=1)
    private String     isTaxExcempted ;

    @Column(name="TAX_AMOUNT")
    private Double     taxAmount ;

    @Column(name="TAX_CODE", length=100)
    private String     taxCode ;

    @Column(name="TAX_EXCEMPTION_REFERENCE", length=100)
    private String     taxExcemptionReference ;

    @Column(name="TAX_EXCEMPTION_TYPE", length=1)
    private String     taxExcemptionType ;

    @Column(name="TAX_EXCEMPTION_TYPE_DESC", length=100)
    private String     taxExcemptionTypeDesc ;

    @Column(name="DISCOUNT_COVER_ID")
    private Integer    discountCoverId ;

    @Column(name="DEPENDENT_COVER_YN", length=2)
    private String     dependentCoverYn ;

    @Column(name="DEPENDENT_COVER_ID")
    private Integer    dependentCoverId ;

    @Column(name="IS_SELECTED_YN", length=20)
    private String     isSelectedYn ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="COVER_BASED_ON", length=100)
    private String     coverBasedOn ;

    @Column(name="MULTI_SELECT_YN", length=100)
    private String     multiSelectYn ;

    @Column(name="EXCESS_PERCENT")
    private Double     excessPercent ;

    @Column(name="EXCESS_AMOUNT")
    private Double     excessAmount ;

    @Column(name="EXCESS_DESC", length=500)
    private String     excessDesc ;

    @Column(name="PRO_RATA_YN", length=100)
    private String     proRataYn ;

    @Column(name="PRO_RATA_DESC", length=100)
    private String     proRataDesc ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



