/*
 * Created on 2024-06-19 ( 16:51:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "DocumentTransactionDetails" ( stored in table "document_transaction_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class DocumentTransactionDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     quoteNo ;
    
    private String     requestReferenceNo ;
    
    private Integer    productId ;
    
    private String     companyId ;
    
    private Integer    sectionId ;
    
    private Integer    locationId ;
    
    private Integer    riskId ;
    
    private String     id ;
    
    private String     idType ;
    
    private Integer    uniqueId ;
    
     
}
