/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:16 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "DocumentTransactionDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(DocumentTransactionDetailsId.class)
@Table(name="document_transaction_details")


public class DocumentTransactionDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false, length=20)
    private String     quoteNo ;

    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=100)
    private String     requestReferenceNo ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=100)
    private String     companyId ;

    @Id
    @Column(name="SECTION_ID", nullable=false)
    private Integer    sectionId ;

    @Id
    @Column(name="LOCATION_ID", nullable=false)
    private Integer    locationId ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    @Id
    @Column(name="ID", nullable=false, length=20)
    private String     id ;

    @Id
    @Column(name="ID_TYPE", nullable=false, length=100)
    private String     idType ;

    @Id
    @Column(name="UNIQUE_ID", nullable=false)
    private Integer    uniqueId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="PRODUCT_NAME", length=100)
    private String     productName ;

    @Column(name="SECTION_NAME", length=100)
    private String     sectionName ;

    @Column(name="LOCATION_NAME", length=100)
    private String     locationName ;

    @Column(name="PRODUCT_TYPE", nullable=false, length=20)
    private String     productType ;

    @Column(name="ENDORSEMENT_TYPE")
    private Integer    endorsementType ;

    @Column(name="ENDORSEMENT_TYPE_DESC", length=100)
    private String     endorsementTypeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="ENDORSEMENT_REMARKS", length=500)
    private String     endorsementRemarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_EFFDATE")
    private Date       endorsementEffdate ;

    @Column(name="ORIGINAL_POLICY_NO", length=500)
    private String     originalPolicyNo ;

    @Column(name="ENDT_PREV_POLICY_NO", length=500)
    private String     endtPrevPolicyNo ;

    @Column(name="ENDT_PREV_QUOTE_NO", length=500)
    private String     endtPrevQuoteNo ;

    @Column(name="ENDT_COUNT")
    private BigDecimal endtCount ;

    @Column(name="ENDT_CATEG_DESC", length=100)
    private String     endtCategDesc ;

    @Column(name="IS_FINYN", length=10)
    private String     IsFinaceYn ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=10)
    private String     status ;

    @Column(name="EMI_YN", length=2)
    private String     emiYn ;

    @Column(name="INSTALLMENT_PERIOD", length=100)
    private String     installmentPeriod ;

    @Column(name="NO_OF_INSTALLMENT", length=10)
    private String     noOfInstallment ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="UNIQUE_ID", referencedColumnName="UNIQUE_ID", insertable=false, updatable=false)
    private DocumentUniqueDetails documentUniqueDetails ; 



}



