/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "EserviceTravelDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceTravelDetailsId.class)
@Table(name="eservice_travel_details")


public class EserviceTravelDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    @Id
    @Column(name="TRAVEL_COVER_ID", nullable=false)
    private Integer    travelCoverId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=20)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Column(name="PRODUCT_NAME", length=100)
    private String     productName ;

    @Column(name="SECTION_ID", nullable=false)
    private Integer    sectionId ;
    
    @Column(name = "LOCATION_ID", length = 20)
  	private Integer locationId;

    @Column(name="SECTION_NAME", length=100)
    private String     sectionName ;

    @Column(name="CURRENCY", length=20)
    private String     currency ;

    @Column(name="EXCHANGE_RATE")
    private BigDecimal     exchangeRate ;

    @Column(name="TRAVEL_COVER_DESC", length=250)
    private String     travelCoverDesc ;

    @Column(name="SOURCE_COUNTRY", length=50)
    private String     sourceCountry ;

    @Column(name="SOURCE_COUNTRY_DESC", length=200)
    private String     sourceCountryDesc ;

    @Column(name="DESTINATION_COUNTRY", length=50)
    private String     destinationCountry ;

    @Column(name="DESTINATION_COUNTRY_DESC", length=200)
    private String     destinationCountryDesc ;

    @Column(name="SPORTS_COVER_YN", length=20)
    private String     sportsCoverYn ;

    @Column(name="TERRORISM_COVER_YN", length=20)
    private String     terrorismCoverYn ;

    @Column(name="PLAN_TYPE_ID")
    private Integer    planTypeId ;

    @Column(name="PLAN_TYPE_DESC", length=50)
    private String     planTypeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TRAVEL_START_DATE")
    private Date       travelStartDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TRAVEL_END_DATE")
    private Date       travelEndDate ;

    @Column(name="TRAVEL_COVER_DURATION")
    private Integer    travelCoverDuration ;

    @Column(name="TOTAL_PASSENGERS")
    private Integer    totalPassengers ;

    @Column(name="TOTAL_PREMIUM")
    private Double     totalPremium ;

    @Column(name="AGE")
    private Integer    age ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="HAVEPROMOCODE", length=10)
    private String     havepromocode ;

    @Column(name="PROMOCODE", length=100)
    private String     promocode ;

    @Column(name="COVID_COVER_YN", length=20)
    private String     covidCoverYn ;

    @Column(name="AC_EXECUTIVE_ID")
    private Integer    acExecutiveId ;

    @Column(name="APPLICATION_ID", length=20)
    private String     applicationId ;

    @Column(name="BROKER_CODE", length=20)
    private String     brokerCode ;

    @Column(name="SUB_USER_TYPE", length=20)
    private String     subUserType ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="CUSTOMER_ID", length=20)
    private String     customerId ;

    @Column(name="QUOTE_NO", length=20)
    private String     quoteNo ;

    @Column(name="ADMIN_LOGIN_ID", length=100)
    private String     adminLoginId ;

    @Column(name="ADMIN_REMARKS", length=1000)
    private String     adminRemarks ;

    @Column(name="REJECT_REASON", length=1000)
    private String     rejectReason ;

    @Column(name="REFERAL_CODES", length=200)
    private String     referalCodes ;

    @Column(name="REFERAL_REMARKS", length=500)
    private String     referalRemarks ;

    @Column(name="BDM_CODE", length=20)
    private String     bdmCode ;

    @Column(name="SOURCE_TYPE", length=20)
    private String     sourceType ;

    @Column(name="CUSTOMER_CODE", length=100)
    private String     customerCode ;

    @Column(name="BROKER_BRANCH_CODE", length=20)
    private String     brokerBranchCode ;

    @Column(name="BROKER_BRANCH_NAME", length=100)
    private String     brokerBranchName ;

    @Column(name="COMMISSION_TYPE", length=20)
    private String     commissionType ;

    @Column(name="COMMISSION_TYPE_DESC", length=100)
    private String     commissionTypeDesc ;

    @Column(name="ACTUAL_PREMIUM_LC")
    private Double     actualPremiumLc ;

    @Column(name="ACTUAL_PREMIUM_FC")
    private Double     actualPremiumFc ;

    @Column(name="OVERALL_PREMIUM_LC")
    private Double     overallPremiumLc ;

    @Column(name="OVERALL_PREMIUM_FC")
    private Double     overallPremiumFc ;

    @Column(name="OLD_REQ_REF_NO", length=20)
    private String     oldReqRefNo ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Column(name="BANK_CODE", length=100)
    private String     bankCode ;

    @Column(name="MANUAL_REFERAL_YN", length=10)
    private String     manualReferalYn ;

    @Column(name="ENDORSEMENT_TYPE")
    private Integer    endorsementType ;

    @Column(name="ENDORSEMENT_TYPE_DESC", length=100)
    private String     endorsementTypeDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Column(name="ENDORSEMENT_REMARKS", length=1000)
    private String     endorsementRemarks ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_EFFDATE")
    private Date       endorsementEffdate ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="ENDT_PREV_POLICY_NO", length=100)
    private String     endtPrevPolicyNo ;

    @Column(name="ENDT_PREV_QUOTE_NO", length=100)
    private String     endtPrevQuoteNo ;

    @Column(name="ENDT_COUNT")
    private BigDecimal     endtCount ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Column(name="IS_FINYN", length=10)
    private String     isFinyn ;

    @Column(name="ENDT_CATEG_DESC", length=100)
    private String     endtCategDesc ;

    @Column(name="ENDT_PREMIUM")
    private BigDecimal     endtPremium ;

    @Column(name="TIRA_COVER_NOTE_NO", length=100)
    private String     tiraCoverNoteNo ;

    @Column(name="COMMISSION_PERCENTAGE")
    private BigDecimal     commissionPercentage ;

    @Column(name="VAT_COMMISSION")
    private BigDecimal     vatCommission ;

    @Column(name="VD_REFNO")
    private Long       vdRefno ;

    @Column(name="CD_REFNO")
    private Long       cdRefno ;

    @Column(name="MS_REFNO")
    private Long       msRefno ;

    @Column(name="CUSTOMER_NAME", length=100)
    private String     customerName ;

    @Column(name="AGENCY_CODE", length=100)
    private String     agencyCode ;

    @Column(name="BRANCH_NAME", length=100)
    private String     branchName ;

    @Column(name="SALE_POINT_CODE", length=200)
    private String     salePointCode ;

    @Column(name="FINALIZE_YN", length=2)
    private String     finalizeYn ;

    @Column(name="BROKER_TIRA_CODE", length=100)
    private String     brokerTiraCode ;

    @Column(name="SOURCE_TYPE_ID", length=20)
    private String     sourceTypeId ;

    @Column(name="EMI_YN", length=20)
    private String     emiYn ;

    @Column(name="INSTALLMENT_PERIOD")
    private Integer    installmentPeriod ;

    @Column(name="EMI_PREMIUM")
    private Double     emiPremium ;

    @Column(name="NO_OF_INSTALLMENT")
    private Integer    noOfInstallment ;

    @Column(name="VAT_PREMIUM")
    private Double     vatPremium ;

    @Column(name="ENDT_VAT_PREMIUM")
    private Double     endtVatPremium ;

    @Column(name="RENEWAL_DATE_YN", length=5)
    private String     renewalDateYn ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



