/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.eway.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "EserviceDriverDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceDriverDetailsId.class)
@Table(name = "eservice_driver_details")

public class EserviceDriverDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "REQUEST_REFERENCE_NO", nullable = false, length = 100)
	private String requestReferenceNo;

	@Id
	@Column(name = "RISK_ID", nullable = false)
	private Integer riskId;

	@Id
	@Column(name = "DRIVER_ID", nullable = false)
	private Integer driverId;

	@Id
	@Column(name = "DD_REFNO", nullable = false)
	private Long ddRefno;

	// --- ENTITY DATA FIELDS
	@Column(name = "QUOTE_NO", length = 100)
	private String quoteNo;

	@Column(name = "DRIVER_NAME", length = 200)
	private String driverName;

	@Column(name = "DRIVER_TYPE", length = 100)
	private String driverType;

	@Column(name = "DRIVER_TYPEDESC", length = 100)
	private String driverTypedesc;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DRIVER_DOB")
	private Date driverDob;

	@Column(name = "STATE_ID", length = 50)
	private String stateId;

	@Column(name = "CITY_ID")
	private Integer cityId;

	@Column(name = "CITY", length = 50)
	private String city;

	@Column(name = "SUBURB_ID")
	private Integer suburbId;

	@Column(name = "SUBURB", length = 50)
	private String suburb;

	@Column(name = "AREA_GROUP")
	private Integer areaGroup;

	@Column(name = "LICENSE_NUMBER", length = 100)
	private String licenseNumber;

	@Temporal(TemporalType.DATE)
	@Column(name = "LICENSE_ISSUE_DT")
	private Date licenseIssueDt;

	@Column(name = "LICENSE_EXPERIENCE")
	private Integer licenseExperience;

	@Column(name = "COUNTRY_ID", length = 5)
	private String countryId;

	@Column(name = "COUNTRY_NAME", length = 100)
	private String countryName;

	@Column(name = "DRIVER_AGE")
	private Integer driverAge;

	@Column(name = "DRIVER_GENDER", length = 5)
	private String driverGender;

	@Column(name = "MARITAL_STATUS", length = 10)
	private String maritalStatus;

	@Column(name = "VD_REFNO")
	private Long vdRefno;

	@Column(name = "CD_REFNO")
	private Long cdRefno;

	@Column(name = "MS_REFNO")
	private Long msRefno;

	@Column(name = "ENDORSEMENT_TYPE")
	private Integer endorsementType;

	@Column(name = "ENDORSEMENT_TYPE_DESC", length = 100)
	private String endorsementTypeDesc;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDORSEMENT_DATE")
	private Date endorsementDate;

	@Column(name = "ENDORSEMENT_REMARKS", length = 500)
	private String endorsementRemarks;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDORSEMENT_EFFDATE")
	private Date endorsementEffdate;

	@Column(name = "ORIGINAL_POLICY_NO", length = 500)
	private String originalPolicyNo;

	@Column(name = "ENDT_PREV_POLICY_NO", length = 500)
	private String endtPrevPolicyNo;

	@Column(name = "ENDT_PREV_QUOTE_NO", length = 500)
	private String endtPrevQuoteNo;

	@Column(name = "ENDT_COUNT")
	private BigDecimal endtCount;

	@Column(name = "ENDT_CATEG_DESC", length = 100)
	private String endtCategDesc;

	@Column(name = "IS_FINYN", length = 10)
	private String isFinyn;

	@Column(name = "ENDT_STATUS", length = 10)
	private String endtStatus;

	@Column(name = "COMPANY_ID", length = 100)
	private String companyId;

	@Column(name = "PRODUCT_ID")
	private Integer productId;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;

	@Column(name = "STATUS", length = 2)
	private String status;

	@Column(name = "CREATED_BY", length = 100)
	private String createdBy;

	@Column(name = "CLAIM_TYPE", length = 5)
	private String claimType;

	@Column(name = "CLAIM_TYPE_DESC", length = 100)
	private String claimTypeDesc;

	@Column(name = "OLD_REQ_REF_NO", length = 20)
	private String oldReqRefNo;

	// --- ENTITY LINKS ( RELATIONSHIP )

//	@Column(name = "DRIVING_LICENSE_AGE")
//	private Integer drivingLicenseAge;

	
}
