/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:31 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:31 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "EserviceLifeDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceLifeDetailsId.class)
@Table(name="eservice_life_details")


public class EserviceLifeDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="AC_EXECUTIVE_ID")
    private Integer    acExecutiveId ;

    @Column(name="VD_REFNO")
    private Long       vdRefno ;

    @Column(name="ACTUAL_PREMIUM_FC")
    private Double     actualPremiumFc ;

    @Column(name="ACTUAL_PREMIUM_LC")
    private Double     actualPremiumLc ;

    @Column(name="ADMIN_LOGIN_ID", length=100)
    private String     adminLoginId ;

    @Column(name="ADMIN_REMARKS", length=100)
    private String     adminRemarks ;

    @Column(name="AGENCY_CODE", length=20)
    private String     agencyCode ;

    @Column(name="AMEND_ID")
    private Integer    amendId ;

    @Column(name="APPLICATION_ID", length=20)
    private String     applicationId ;

    @Column(name="BANK_CODE", length=100)
    private String     bankCode ;

    @Column(name="BDM_CODE", length=100)
    private String     bdmCode ;

    @Column(name="BROKER_BRANCH_CODE", length=20)
    private String     brokerBranchCode ;

    @Column(name="BROKER_BRANCH_NAME", length=100)
    private String     brokerBranchName ;

    @Column(name="BROKER_CODE", length=20)
    private String     brokerCode ;

    @Column(name="CD_REFNO")
    private Long       cdRefno ;

    @Column(name="COMMISSION_PERCENTAGE")
    private Double     commissionPercentage ;

    @Column(name="COMPANY_ID", length=20)
    private String     companyId ;

    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="CURRENCY", length=20)
    private String     currency ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_DATE")
    private Date       endorsementDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENDORSEMENT_EFFDATE")
    private Date       endorsementEffdate ;

    @Column(name="ENDORSEMENT_REMARKS", length=1000)
    private String     endorsementRemarks ;

    @Column(name="ENDORSEMENT_TYPE")
    private Integer    endorsementType ;

    @Column(name="ENDORSEMENT_TYPE_DESC", length=100)
    private String     endorsementTypeDesc ;

    @Column(name="ENDT_CATEG_DESC", length=100)
    private String     endtCategDesc ;

    @Column(name="ENDT_COUNT")
    private Double     endtCount ;

    @Column(name="ENDT_PREMIUM")
    private Double     endtPremium ;

    @Column(name="ENDT_PREV_POLICY_NO", length=100)
    private String     endtPrevPolicyNo ;

    @Column(name="ENDT_PREV_QUOTE_NO", length=100)
    private String     endtPrevQuoteNo ;

    @Column(name="ENDT_STATUS", length=10)
    private String     endtStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="EXCHANGE_RATE")
    private BigDecimal     exchangeRate ;

    @Column(name="HAVEPROMOCODE", length=10)
    private String     havepromocode ;

    @Column(name="IS_FINYN", length=10)
    private String     isFinyn ;

    @Column(name="LOGIN_ID", length=100)
    private String     loginId ;

    @Column(name="MANUAL_REFERAL_YN", length=100)
    private String     manualReferalYn ;

    @Column(name="MS_REFNO")
    private Long       msRefno ;

    @Column(name="ORIGINAL_POLICY_NO", length=100)
    private String     originalPolicyNo ;

    @Column(name="OVERALL_PREMIUM_FC")
    private Double     overallPremiumFc ;

    @Column(name="OVERALL_PREMIUM_LC")
    private Double     overallPremiumLc ;

    @Column(name="PERIOD_OF_INSURANCE", length=10)
    private String     periodOfInsurance ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICY_END_DATE")
    private Date       policyEndDate ;

    @Column(name="POLICY_NO", length=100)
    private String     policyNo ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICY_START_DATE")
    private Date       policyStartDate ;

    @Column(name="PRODUCT_DESC", length=100)
    private String     productDesc ;

    @Column(name="PRODUCT_ID", length=20)
    private String     productId ;

    @Column(name="PROMOCODE", length=100)
    private String     promocode ;

    @Column(name="QUOTE_NO", length=20)
    private String     quoteNo ;

    @Column(name="REFERAL_REMARKS", length=500)
    private String     referalRemarks ;

    @Column(name="REJECT_REASON", length=100)
    private String     rejectReason ;

    @Column(name="SECTION_DESC", length=100)
    private String     sectionDesc ;

    @Column(name="SECTION_ID", length=20)
    private String     sectionId ;

    @Column(name="SOURCE_TYPE", length=100)
    private String     sourceType ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Column(name="SUB_USER_TYPE", length=30)
    private String     subUserType ;

    @Column(name="SUM_INSURED")
    private BigDecimal     sumInsured ;

    @Column(name="SUM_INSURED_LC")
    private BigDecimal     sumInsuredLc ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="VAT_COMMISSION")
    private Double     vatCommission ;

    @Column(name="POLICY_TERM")
    private Integer    policyTerm ;

    @Column(name="PREMIUM_PAYING_TERM")
    private Integer    premiumPayingTerm ;

    @Column(name="PAYMENT_MODE", length=10)
    private String     paymentMode ;

    @Column(name="PAYMENT_MODE_DESC", length=100)
    private String     paymentModeDesc ;

    @Column(name="ASSURED_NAME", length=100)
    private String     assuredName ;

    @Column(name="MOBILE_NO", length=20)
    private String     mobileNo ;

    @Temporal(TemporalType.DATE)
    @Column(name="DOB")
    private Date       dob ;

    @Column(name="AGE")
    private Integer    age ;

    @Column(name="GENDER", length=6)
    private String     gender ;

    @Column(name="GENDER_DESC", length=15)
    private String     genderDesc ;

    @Column(name="ADDRESS", length=100)
    private String     address ;

    @Column(name="PO_BOX", length=20)
    private String     poBox ;

    @Column(name="CITY", length=100)
    private String     city ;

    @Column(name="NATIONALITY", length=50)
    private String     nationality ;

    @Column(name="MARITAL_STATUS", length=5)
    private String     maritalStatus ;

    @Column(name="RELATION", length=30)
    private String     relation ;

    @Column(name="RELATION_DESC", length=30)
    private String     relationDesc ;

    @Column(name="MAIN_MEMBER_YN", length=5)
    private String     mainMemberYn ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="CUSTOMER_CODE", length=20)
    private String     customerCode ;

    @Column(name="CUSTOMER_NAME", length=200)
    private String     customerName ;

    @Column(name="BRANCH_NAME", length=100)
    private String     branchName ;

    @Column(name="INSURANCE_TYPE", length=50)
    private String     insuranceType ;

    @Column(name="ENDT_CATEGORY_ID")
    private Integer    endtCategoryId ;

    @Column(name="EMI_YN", length=20)
    private String     emiYn ;

    @Column(name="INSTALLMENT_PERIOD")
    private Integer    installmentPeriod ;

    @Column(name="EMI_PREMIUM")
    private Double     emiPremium ;

    @Column(name="NO_OF_INSTALLMENT")
    private Integer    noOfInstallment ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



