/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:51:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:51:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "EserviceCustomerDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EserviceCustomerDetailsId.class)
@Table(name="eservice_customer_details")


public class EserviceCustomerDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CLIENT_NAME", length=250)
    private String     clientName ;

    @Column(name="ADDRESS_1", length=100)
    private String     address1 ;

    @Column(name="ADDRESS_2", length=100)
    private String     address2 ;

    @Column(name="TITLE", length=1)
    private String     title ;

    @Column(name="TITLE_DESC", length=20)
    private String     titleDesc ;

    @Column(name="VR_TIN_NO", length=20)
    private String     vrTinNo ;

    @Column(name="CLIENT_STATUS", length=20)
    private String     clientStatus ;

    @Column(name="CLIENT_STATUS_DESC", length=100)
    private String     clientStatusDesc ;

    @Column(name="POLICY_HOLDER_TYPE", length=2)
    private String     policyHolderType ;

    @Column(name="POLICY_HOLDER_TYPEID", nullable=false, length=100)
    private String     policyHolderTypeid ;

    @Column(name="ID_NUMBER", nullable=false, length=100)
    private String     idNumber ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DOB_OR_REG_DATE")
    private Date       dobOrRegDate ;

    @Column(name="AGE", nullable=false)
    private Integer    age ;

    @Column(name="NATIONALITY", length=20)
    private String     nationality ;

    @Column(name="PLACE_OF_BIRTH", length=100)
    private String     placeOfBirth ;

    @Column(name="GENDER", nullable=false, length=1)
    private String     gender ;

    @Column(name="GENDER_DESC", length=20)
    private String     genderDesc ;

    @Column(name="OCCUPATION", nullable=false, length=10)
    private String     occupation ;

    @Column(name="OCCUPATION_DESC", length=1500)
    private String     occupationDesc ;

    @Column(name="BUSINESS_TYPE", length=1)
    private String     businessType ;

    @Column(name="BUSINESS_TYPE_DESC", length=20)
    private String     businessTypeDesc ;

    @Column(name="VRN_GST", length=20)
    private String     vrnGst ;

    @Column(name="REGION_CODE", length=20)
    private String     regionCode ;

    @Column(name="STATE_CODE", length=20)
    private String     stateCode ;

    @Column(name="STATE_NAME", length=100)
    private String     stateName ;

    @Column(name="CITY_CODE", length=20)
    private String     cityCode ;

    @Column(name="CITY_NAME", length=100)
    private String     cityName ;

    @Column(name="STREET", length=100)
    private String     street ;

    @Column(name="FAX", length=20)
    private String     fax ;

    @Column(name="TELEPHONE_NO_1", length=20)
    private String     telephoneNo1 ;

    @Column(name="TELEPHONE_NO_2", length=20)
    private String     telephoneNo2 ;

    @Column(name="TELEPHONE_NO_3", length=20)
    private String     telephoneNo3 ;

    @Column(name="MOBILE_CODE_1", length=20)
    private String     mobileCode1 ;

    @Column(name="MOBILE_CODE_DESC_1", length=20)
    private String     mobileCodeDesc1 ;

    @Column(name="MOBILE_NO_1", length=20)
    private String     mobileNo1 ;

    @Column(name="MOBILE_CODE_2", length=20)
    private String     mobileCode2 ;

    @Column(name="MOBILE_CODE_DESC_2", length=20)
    private String     mobileCodeDesc2 ;

    @Column(name="MOBILE_NO_2", length=20)
    private String     mobileNo2 ;

    @Column(name="MOBILE_CODE_3", length=20)
    private String     mobileCode3 ;

    @Column(name="MOBILE_CODE_DESC_3", length=20)
    private String     mobileCodeDesc3 ;

    @Column(name="MOBILE_NO_3", length=20)
    private String     mobileNo3 ;

    @Column(name="EMAIL_1", length=100)
    private String     email1 ;

    @Column(name="EMAIL_2", length=20)
    private String     email2 ;

    @Column(name="EMAIL_3", length=20)
    private String     email3 ;

    @Column(name="WHATSAPP_CODE", length=20)
    private String     whatsappCode ;

    @Column(name="WHATSAPP_CODE_DESC", length=20)
    private String     whatsappCodeDesc ;

    @Column(name="WHATSAPP_NO", length=20)
    private String     whatsappNo ;

    @Column(name="LANGUAGE", length=1)
    private String     language ;

    @Column(name="LANGUAGE_DESC", length=20)
    private String     languageDesc ;

    @Column(name="IS_TAX_EXEMPTED", nullable=false, length=1)
    private String     isTaxExempted ;

    @Column(name="TAX_EXEMPTED_ID", length=20)
    private String     taxExemptedId ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="ID_TYPE", length=100)
    private String     idType ;

    @Column(name="ID_TYPE_DESC", length=100)
    private String     idTypeDesc ;

    @Column(name="POLICY_HOLDER_TYPE_DESC", length=100)
    private String     policyHolderTypeDesc ;

    @Column(name="POLICY_HOLDER_TYPE_ID_DESC", length=100)
    private String     policyHolderTypeIdDesc ;

    @Column(name="BROKER_BRANCH_CODE", length=20)
    private String     brokerBranchCode ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPOINTMENT_DATE")
    private Date       appointmentDate ;

    @Column(name="PREFERRED_NOTIFICATION", length=100)
    private String     preferredNotification ;

    @Column(name="PIN_CODE", length=20)
    private String     pinCode ;

    @Column(name="POLICY_HODER_TYPE_DESC", length=50)
    private String     policyHoderTypeDesc ;

    @Column(name="POLICY_HODER_TYPE_ID_DESC", length=50)
    private String     policyHoderTypeIdDesc ;

    @Column(name="OTHER_OCCUPATION", length=200)
    private String     otherOccupation ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LICENSE_ISSUED_DATE")
    private Date       licenseIssuedDate ;

    @Column(name="LICESENSE_DURATION")
    private Integer    licesenseDuration ;

    @Column(name="AREA_GROUP", length=100)
    private String     areaGroup ;

    @Column(name="AREA_CLARIFICATION", length=100)
    private String     areaClarification ;

    @Column(name="AREA_CLASIFICATION", length=10)
    private String     areaClasification ;

    @Column(name="LICENSE_DURATION")
    private Integer    licenseDuration ;

    @Column(name="MARITAL_STATUS", length=100)
    private String     maritalStatus ;

    @Column(name="MARITAL_STATUS_DESC", length=100)
    private String     maritalStatusDesc ;

    @Column(name="POL_CUST_CODE", length=50)
    private String     polCustCode ;

    @Column(name="SUB_URB_ID")
    private Integer    subUrbId ;

    @Column(name="FIRST_NAME", length=200)
    private String     firstName ;

    @Column(name="MIDDLE_NAME", length=200)
    private String     middleName ;

    @Column(name="LAST_NAME", length=200)
    private String     lastName ;

    @Column(name="CUSTOMER_CODE", length=100)
    private String     customerCode ;

    @Column(name="ADDRESS_3", length=100)
    private String     address3 ;

    @Column(name = "ZONE")
	private Integer zone;
    
    @Column(name="COUNTRY", length=50)
    private String     country ;
    
    @Column(name="COUNTRY_NAME", length=100)
    private String     countryName ;
    
    @Column(name="NATIONALITY_NAME", length=100)
    private String     nationalityName ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRY_DATE")
    private Date expiryDate;
}



