/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:52:41 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:52:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.*;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;




/**
* Domain class for entity "FactorTypeDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(FactorTypeDetailsId.class)
@Table(name="factor_type_details")


public class FactorTypeDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="FACTOR_TYPE_ID", nullable=false)
    private Integer    factorTypeId ;

    @Id
    @Column(name="RATING_FIELD_ID", nullable=false)
    private Integer    ratingFieldId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=20)
    private String     companyId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="FACTOR_TYPE_NAME", length=100)
    private String     factorTypeName ;

    @Column(name="FACTOR_TYPE_DESC", length=100)
    private String     factorTypeDesc ;

    @Column(name="RANGE_YN", length=1)
    private String     rangeYn ;

    @Column(name="RANGE_FROM_COLUMN", length=100)
    private String     rangeFromColumn ;

    @Column(name="FROM_DISPLAY_NAME", length=100)
    private String     fromDisplayName ;

    @Column(name="RANGE_TO_COLUMN", length=100)
    private String     rangeToColumn ;

    @Column(name="TO_DISPLAY_NAME", length=100)
    private String     toDisplayName ;

    @Column(name="DISCRETE_COLUMN", length=100)
    private String     discreteColumn ;

    @Column(name="DISCRETE_DISPLAY_NAME", length=100)
    private String     discreteDisplayName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="COLUMNS_ID")
    private Integer    columnsId ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="MASTER_YN", length=2)
    private String     masterYn ;

    @Column(name="API_URL", length=100)
    private String     apiUrl ;

    @Column(name="FACTOR_TYPE_NAME_LOCAL", length=100)
    private String     factorTypeNameLocal ;

    @Column(name="FACTOR_TYPE_DESC_LOCAL", length=100)
    private String     factorTypeDescLocal ;

    @Column(name="FROM_DISPLAY_NAME_LOCAL", length=100)
    private String     fromDisplayNameLocal ;

    @Column(name="TO_DISPLAY_NAME_LOCAL", length=100)
    private String     toDisplayNameLocal ;

    @Column(name="DISCRETE_COLUMN_NAME_LOCAL", length=100)
    private String     discreteColumnNameLocal ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



