/*
 * Created on 2024-06-19 ( 16:52:44 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "IndustryMaster" ( stored in table "industry_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class IndustryMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    industryId ;
    
    private String     categoryId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private String     productId ;
    
     
}
