/*
 * Created on 2024-06-19 ( 16:53:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "MsLifeDetails" ( stored in table "ms_life_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MsLifeDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Long       vdRefno ;
    
    private Integer    riskId ;
    
    private String     branchCode ;
    
    private Integer    productId ;
    
    private Integer    sectionId ;
    
    private String     companyId ;
    
    private String     currency ;
    
    private Double     exchangeRate ;
    
    private String     periodOfInsurance ;
    
    private Double     sumInsured ;
    
    private String     status ;
    
    private Integer    groupCount ;
    
    private String     havepromocode ;
    
    private String     promocode ;
    
    private Double     uwLoading ;
    
     
}
