/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:53:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:53:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "MsVehicleDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MsVehicleDetailsId.class)
@Table(name="ms_vehicle_details")


public class MsVehicleDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="VEHICLE_ID", nullable=false, length=10)
    private String     vehicleId ;

	@Id
	@Column(name = "LOCATION_ID", nullable = false, length = 10)
	private Integer locationId;

    @Id
    @Column(name="CHASSIS_NUMBER", nullable=false, length=20)
    private String     chassisNumber ;

    @Id
    @Column(name="VD_REFNO", nullable=false)
    private Long       vdRefno ;

    @Id
    @Column(name="STATUS", nullable=false, length=20)
    private String     status ;

    @Id
    @Column(name="ENDT_TYPE_ID", nullable=false)
    private Integer    endtTypeId ;

    @Id
    @Column(name="ENDT_CATEGORY_ID", nullable=false, length=50)
    private String     endtCategoryId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="REQUEST_REFERENCE_NO", length=100)
    private String     requestReferenceNo ;

    @Column(name="ACCIDENT_YN", length=20)
    private String     accidentYn ;

    @Column(name="WIND_SCREEN_COVER_REQUEIRED", nullable=false, length=50)
    private String     windScreenCoverRequeired ;

    @Column(name="INSURANCE_TYPE", nullable=false, length=10)
    private String     insuranceType ;

    @Column(name="INSURANCE_CLASS", nullable=false, length=10)
    private String     insuranceClass ;

    @Column(name="OWNER_CATEGORY", length=50)
    private String     ownerCategory ;

    @Column(name="VEHICLE_MAKE", nullable=false, length=50)
    private String     vehicleMake ;

    @Column(name="VEHCILE_MODEL", nullable=false, length=50)
    private String     vehcileModel ;

    @Column(name="VEHICLE_BODY_TYPE", nullable=false, length=50)
    private String     vehicleBodyType ;

    @Column(name="FUEL_TYPE", length=50)
    private String     fuelType ;

    @Column(name="MANUFACTURE_YEAR", nullable=false)
    private Integer    manufactureYear ;

    @Column(name="MANUFACTURE_AGE", nullable=false)
    private Integer    manufactureAge ;

    @Column(name="REGISTRATION_AGE")
    private Integer    registrationAge ;

    @Temporal(TemporalType.DATE)
    @Column(name="REGISTRATION_YEAR")
    private Date       registrationYear ;

    @Column(name="SEATING_CAPACITY", nullable=false, length=20)
    private String     seatingCapacity ;

    @Column(name="PERIOD_OF_INSURANCE", nullable=false, length=10)
    private String     periodOfInsurance ;

    @Column(name="WIND_SCREEN_SUM_INSURED")
    private BigDecimal     windScreenSumInsured ;

    @Column(name="ACCCESSORIES_SUM_INSURED")
    private BigDecimal     acccessoriesSumInsured ;

    @Column(name="SUM_INSURED")
    private BigDecimal     sumInsured ;

    @Column(name="NCDYEARS", nullable=false)
    private Integer    ncdyears ;

    @Column(name="NCD_YN", nullable=false, length=5)
    private String     ncdYn ;

    @Column(name="NO_OF_CLAIMS", nullable=false)
    private Integer    noOfClaims ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE", nullable=false)
    private Date       entryDate ;

    @Column(name="VEHICLE_WEIGHT")
    private BigDecimal     vehicleWeight ;

    @Column(name="CURRENCY", nullable=false, length=100)
    private String     currency ;

    @Column(name="EXCHANGE_RATE", nullable=false)
    private BigDecimal     exchangeRate ;

    @Column(name="FLEET_OWNER_YN", nullable=false, length=1)
    private String     fleetOwnerYn ;

    @Column(name="NO_OF_VEHICLES", nullable=false)
    private Integer    noOfVehicles ;

    @Column(name="NO_OF_COMPEHENSIVES", nullable=false)
    private Integer    noOfCompehensives ;

    @Column(name="CLAIM_RATIO", nullable=false)
    private BigDecimal     claimRatio ;

    @Column(name="TPD_INCREASE_LIMIT")
    private BigDecimal     tpdIncreaseLimit ;

    @Column(name="MOTOR_USAGE", length=100)
    private String     motorUsage ;

    @Column(name="GPS_YN", length=5)
    private String     gpsYn ;

    @Column(name="GROUP_COUNT")
    private Integer    groupCount ;

    @Column(name="CITY_LIMIT", length=20)
    private String     cityLimit ;

    @Column(name="HAVEPROMOCODE", length=10)
    private String     havepromocode ;

    @Column(name="PROMOCODE", length=100)
    private String     promocode ;

    @Column(name="WIND_SCREEN_SUM_INSURED_LC")
    private BigDecimal     windScreenSumInsuredLc ;

    @Column(name="ACCCESSORIES_SUM_INSURED_LC")
    private BigDecimal     acccessoriesSumInsuredLc ;

    @Column(name="SUM_INSURED_LC")
    private BigDecimal     sumInsuredLc ;

    @Column(name="TPPD_INCREAE_LIMIT_LC")
    private BigDecimal     tppdIncreaeLimitLc ;

    @Column(name="TPPD_FREE_LIMIT_LC")
    private BigDecimal     tppdFreeLimitLc ;

    @Column(name="TPPD_FREE_LIMIT")
    private BigDecimal     tppdFreeLimit ;

    @Column(name="LOADING_PERCENT")
    private BigDecimal     loadingPercent ;

    @Column(name="UW_LOADING")
    private BigDecimal     uwLoading ;

    @Column(name="CUBIC_CAPACITY")
    private BigDecimal     cubicCapacity ;

    @Column(name="SOURCE_TYPE", length=100)
    private String     sourceType ;

    @Column(name="NON_ELEC_ACCESSORIES_SI")
    private BigDecimal     nonElecAccessoriesSi ;

    @Column(name="NON_ELEC_ACCESSORIES_SI_LC")
    private BigDecimal     nonElecAccessoriesSiLc ;

    @Column(name="EXCESS_LIMIT")
    private BigDecimal     excessLimit ;

    @Column(name="EXCESS_LIMIT_LC")
    private BigDecimal     excessLimitLc ;

    @Column(name="MANUFACTURE_COUNTRY", length=25)
    private String     manufactureCountry ;

    @Column(name="CUSTOMER_TYPE", length=25)
    private String     customerType ;

    @Column(name="VEHICLE_MAKE_ID", length=10)
    private String     vehicleMakeId ;

    @Column(name="VEHICLE_MODEL_ID", length=10)
    private String     vehicleModelId ;

    @Column(name="FUEL_TYPE_ID", length=10)
    private String     fuelTypeId ;

    @Column(name="DRIVEN_BY", length=5)
    private String     drivenBy ;

    @Column(name="OWNER_CATEGORY_ID", length=10)
    private String     ownerCategoryId ;

    @Column(name="OWN_DAMAGE", length=100)
    private String     ownDamage ;

    @Column(name="THEFT", length=100)
    private String     theft ;

    @Column(name="WINDSCREEN", length=100)
    private String     windscreen ;

    @Column(name="FIRE", length=100)
    private String     fire ;

    @Column(name="THIRD_PARTY", length=100)
    private String     thirdParty ;

    @Column(name="VEHICLE_CLASS", length=100)
    private String     vehicleClass ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LICENSE_ISSUED_DATE")
    private Date       licenseIssuedDate ;

    @Column(name="LICENSE_DURATION")
    private Integer    licenseDuration ;

    @Column(name="CLAIM_NUM_12M_0M")
    private Integer    claimNum12m0m ;

    @Column(name="CLAIM_NUM_24M_12M")
    private Integer    claimNum24m12m ;

    @Column(name="CLAIM_NUM_36M_24M")
    private Integer    claimNum36m24m ;

    @Column(name="POWER_KILO_WATTS")
    private BigDecimal     powerKiloWatts ;

    @Column(name="POWER_WATTS")
    private BigDecimal     powerWatts ;

    @Column(name="VEHICLE_GROUP", length=10)
    private String     vehicleGroup ;

    @Column(name="CAR_ALARM_YN", length=10)
    private String     carAlarmYn ;

    @Column(name="PAYMENT_FREQUENCY")
    private Integer    paymentFrequency ;

    @Column(name="EXCESS", length=100)
    private String     excess ;

    @Column(name="VEHICLE_VALUE_TYPE", length=100)
    private String     vehicleValueType ;

    @Column(name="INFLATION", length=100)
    private String     inflation ;

    @Column(name="DEFENCE_VALUE", length=100)
    private String     defenceValue ;

    @Column(name="NCB", length=100)
    private String     ncb ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PURCHASE_DATE")
    private Date       purchaseDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REGISTRATION_DATE")
    private Date       registrationDate ;

    @Column(name="VEHICLE_VALUE_TYPE_DESC", length=100)
    private String     vehicleValueTypeDesc ;

    @Column(name="CLAIM_TYPE", length=20)
    private String     claimType ;

    

    @Column(name="RENEWAL_YN", length=2)
    private String     renewalYn ;

//    @Column(name="RENEWAL_DATE_YN", length=2)
//    private String     renewalDateYn ;

    @Column(name="CUST_RENEWAL_YN", length=5)
    private String     custRenewalYn ;

    @Column(name="LOSS_RATIO")
    private BigDecimal     lossRatio ;

    @Column(name="PREVIOUS_INSURANCE_YN", length=2)
    private String     previousInsuranceYn ;

	@Column(name = "RENEWAL_DATE_YN", length = 2)
	private String renewalDateYN;
	
	@Column(name = "HORSE_POWER")
	private Integer horsePower;
	
	  @Column(name = "ZONE")
	private Integer zone;
	  
	@Column(name = "CLASS")
	private String classType;

	@Column(name = "NO_OF_CARDS")
	private Integer noOfCards;

	@Column(name = "PAYLOAD")
	private BigDecimal payload;
	
	@Column(name = "PA_COVERID")
    private String paCoverId;
	
	@Column(name = "NO_OF_CYLINDERS")
    private Integer noOfCylinders;
	
	@Column(name = "DISPLACEMENT_CM3")
    private String displacementInCM3;


}



