/*
 * Created on 2024-06-19 ( 16:53:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "PolicyCoverDataIndividuals" ( stored in table "policy_cover_data_individuals" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class PolicyCoverDataIndividualsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     quoteNo ;
    
    private String     requestReferenceNo ;
    
    private Integer    vehicleId ;
    
    private Integer    productId ;
    
    private Integer    sectionId ;
    
    private Integer    coverId ;
    
    private String     subCoverYn ;
    
    private Integer    subCoverId ;
    
    private Integer    discLoadId ;
    
    private Integer    taxId ;
    
    private Double     endtCount ;
    
    private Integer    discountCoverId ;
    
    private Integer    individualId ;
    
    private Integer    locationId ;
    
     
}
