/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-06-19 ( Date ISO 2024-06-19 - Time 16:53:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-06-19 ( 16:53:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.*;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;




/**
* Domain class for entity "ProductBenefitMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ProductBenefitMasterId.class)
@Table(name="product_benefit_master")


public class ProductBenefitMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BENEFIT_ID", nullable=false)
    private Integer    benefitId ;

    @Id
    @Column(name="TYPE_ID", nullable=false)
    private Integer    typeId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=100)
    private String     companyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="SECTION_ID", nullable=false)
    private Integer    sectionId ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BENEFIT_DESCRIPTION", length=100)
    private String     benefitDescription ;

    @Column(name="TYPE_DESC", length=100)
    private String     typeDesc ;

    @Column(name="ICON_PATH", length=500)
    private String     iconPath ;

    @Column(name="ORIGINAL_IMAGE_PATH", length=500)
    private String     originalImagePath ;

    @Column(name="COMPANY_NAME", length=100)
    private String     companyName ;

    @Column(name="PRODUCT_DESC", length=100)
    private String     productDesc ;

    @Column(name="SECTION_DESC", length=100)
    private String     sectionDesc ;

    @Column(name="COVER_ID")
    private Integer    coverId ;

    @Column(name="COVER_NAME", length=100)
    private String     coverName ;

    @Column(name="SUB_COVER_ID")
    private Integer    subCoverId ;

    @Column(name="SUB_COVER_NAME", length=100)
    private String     subCoverName ;

    @Column(name="LONG_DESC", length=500)
    private String     longDesc ;

    @Column(name="CALC_TYPE", length=20)
    private String     calcType ;

    @Column(name="CALC_TYPE_DESC", length=100)
    private String     calcTypeDesc ;

    @Column(name="VALUE")
    private Double     value ;

    @Column(name="AGENCY_CODE", length=20)
    private String     agencyCode ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;

    @Column(name="DISPLAY_ORDER")
    private Integer    displayOrder ;

    @Column(name="STATUS", length=10)
    private String     status ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="CORE_APP_CODE", length=100)
    private String     coreAppCode ;

    @Column(name="REGULATORY_CODE", length=100)
    private String     regulatoryCode ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="BENEFIT_DESCRIPTION_LOCAL", length=100)
    private String     benefitDescriptionLocal ;

    @Column(name="TYPE_DESC_LOCAL", length=100)
    private String     typeDescLocal ;

    @Column(name="COMPANY_NAME_LOCAL", length=100)
    private String     companyNameLocal ;

    @Column(name="PRODUCT_DESC_LOCAL", length=100)
    private String     productDescLocal ;

    @Column(name="SECTION_DESC_LOCAL", length=100)
    private String     sectionDescLocal ;

    @Column(name="COVER_NAME_LOCAL", length=100)
    private String     coverNameLocal ;

    @Column(name="SUB_COVER_NAME_LOCAL", length=100)
    private String     subCoverNameLocal ;

    @Column(name="LONG_DESC_LOCAL", length=500)
    private String     longDescLocal ;

    @Column(name="CALC_TYPE_DESC_LOCAL", length=100)
    private String     calcTypeDescLocal ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



