/*
 * Created on 2023-09-21 ( 13:32:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "SurvivalBenefitMaster" ( stored in table "survival_benefit_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class SurvivalBenefitMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    
    private Integer    sno ;
    
    private Integer    policyTerms ;
    
    private Integer    endOfYear ;
    
//    private Double     amount ;
    
  //  private String     status ;
    
    private Integer    amendId ;
    
    private Integer    productId ;
    
    private Integer    sectionId ;
    
    private String     companyId ;
    
     
}
