/*
 * Created on 2024-06-19 ( 16:54:37 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "TaxExemptionSetup" ( stored in table "tax_exemption_setup" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class TaxExemptionSetupId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    productId ;
    
    private Integer    sectionId ;
    
    private Integer    coverId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private Integer    taxId ;
    
    private Integer    amendId ;
    
    private String     taxFor ;
    
    private String     countryId ;
    
     
}
