/*
 * Created on 2024-06-19 ( 16:54:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "WarrantyMaster" ( stored in table "warranty_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class WarrantyMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    warrantyId ;
    
    private String     branchCode ;
    
    private String     companyId ;
    
    private String     productId ;
    
    private Integer    amendId ;
    
    private String     sectionId ;
    
     
}
